remote_theme: mmistakes/minimal-mistakes@4.28.1
plugins:
- jekyll-remote-theme
- jekyll-include-cache
title: Undervisningsmaterial
minimal_mistakes_skin: "dirt"
locale: "se"
name: "Svante Daneklev Wold"
